### 리뷰 등록 API(이미지 없이 등록)
POST http://localhost:8080/products/3/reviews
Content-Type: multipart/form-data; boundary=----boundary

------boundary
Content-Disposition: form-data; name="review"
Content-Type: application/json

{
  "userId": 668,
  "score": 2,
  "content": "나름 좋아요"
}
------boundary
Content-Disposition: form-data; name="image";
Content-Type: image/jpeg

------boundary--

### 리뷰 등록 API(이미지 포함 등록)
POST http://localhost:8080/products/5/reviews
Content-Type: multipart/form-data; boundary=----boundary

------boundary
Content-Disposition: form-data; name="review"
Content-Type: application/json

{
  "userId": 111,
  "score": 4,
  "content": "진짜별로임!"
}
------boundary
Content-Disposition: form-data; name="image";  filename="test1.jpg";
Content-Type: image/jpeg

< C:\Users\user\Documents\test1.jpg
------boundary--


### 리뷰 조회 API
GET http://localhost:8080/products/9/reviews?cursor=0&size=2
Accept: application/json