### 리뷰 등록 API (이미지 없이 등록)
POST http://localhost:8080/products/2/reviews
Content-Type: application/json

{
  "userId": 181,
  "score": 5,
  "content": "최고예요!"
}

### 리뷰 등록 API (이미지 포함 등록)
POST http://localhost:8080/products/3/reviews
Content-Type: application/json

{
  "userId": 180,
  "score": 5,
  "content": "정말 마음에 들어요.",
  "imageUrl": "/image.png"
}